Bf5 ww 36
CampusDual/cd2024bfs5g1 pull request #137
Opened 2024-11-27 15:13 UTC by Jul-i-an

Correcciones realizadas.

2024-11-27 15:15 UTC, Jul-i-an commented
César, esta no es la PR que hay que subir, sino la de la rama 107

2024-11-28 07:15 UTC, cesarsantiagonunez requested changes

2024-11-28 07:15 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-detail/coworkings-detail.component.html
> +    columns="cw_id;cw_namecw_address;cw_location"
pode ser que falte un `;`?

2024-11-28 07:15 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-detail/coworkings-detail.component.html
> +    <!-- <o-integer-input oHidden #cw_location attr="cw_location"></o-integer-input> //-->
o codigo comentado borradeo

2024-11-28 07:15 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-new/coworkings-new.component.ts
> +  // mapId: number = 0;
o mismo aqui

2024-11-29 09:22 UTC, cesarsantiagonunez requested changes

2024-11-29 09:22 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-detail/coworkings-detail.component.ts
> +    //this.mapaShow();
o codigo comentado borradeo

2024-11-29 09:22 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/assets/i18n/en.json
> +  "DAILY_PRICE": "day",
esto por que cambiou?

2024-11-29 09:22 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/assets/i18n/en.json
> +  "MYEVENTS": "My Events",
deixadeo como estaba que pediron evitar o camelCase nas traduccions

2024-11-29 09:27 UTC, SergioSanmiguel commented on cd2024bfs5g1-frontend/src/main/ngx/src/assets/i18n/en.json
> +  "DAILY_PRICE": "day",
Petición de Gema

2024-11-29 09:56 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/assets/i18n/en.json
> +  "MYEVENTS": "My Events",
```suggestion
  "MYEVENTS": "My events",
```

2024-11-29 10:46 UTC, cesarsantiagonunez approved these changes
aseguradevos de estar actualizados con develop e mergeade

2024-11-29 10:46 UTC, merged