Bf5 ww 67
CampusDual/cd2024bfs5g1 pull request #83
Opened 2024-11-13 12:11 UTC by natu-al

Actualización de estilos de formularios, detalle de coworking y estilos en general (workwonder.scss)

2024-11-13 13:51 UTC, cesarsantiagonunez requested changes

2024-11-13 13:51 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-detail/coworkings-detail.component.ts
> -
porque se quitou todo este codigo?

2024-11-13 13:51 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-home/coworkings-home.component.html
> -        appearance="outline"
estades elimnando un combo que fai falta

2024-11-13 13:51 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-home/coworkings-home.component.html
> +    gutter-size="20px" pageable="yes">
```suggestion
    gutter-size="40px" pageable="yes">
```

2024-11-13 13:54 UTC, natu-al commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-detail/coworkings-detail.component.ts
> -
Se eliminó el método porque ya no es necesario.

2024-11-14 10:11 UTC, cesarsantiagonunez requested changes

2024-11-14 10:11 UTC, cesarsantiagonunez commented on cd2024bfs5g1-frontend/src/main/ngx/src/app/main/coworkings/coworkings-detail/coworkings-detail.component.ts
> +      console.log(this.realCapacity)
quitade os console logs

2024-11-14 11:12 UTC, cesarsantiagonunez requested changes

2024-11-14 11:12 UTC, cesarsantiagonunez commented on codestyle/codestyle/saveactions_settings.xml
este save actions teria que estar solo dentro da carpeta .idea

2024-11-14 11:48 UTC, merged